@startuml

title __BERTRANDS-PARADOX's Class Diagram__\n

  namespace  {
    namespace h.kbw.app {
      class ch.kbw.app.App {
      }
    }
  }
  

  namespace  {
    namespace h.kbw.app {
      class ch.kbw.app.StartScreenController {
      }
    }
  }
  

  namespace  {
    namespace h.kbw.endpointmethod {
      class ch.kbw.endpointmethod.EndPointController {
      }
    }
  }
  

  namespace  {
    namespace h.kbw.endpointmethod {
      namespace model {
        class ch.kbw.endpointmethod.model.Circle {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.endpointmethod {
      namespace model {
        class ch.kbw.endpointmethod.model.Line {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.endpointmethod {
      namespace model {
        class ch.kbw.endpointmethod.model.LineManager {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.endpointmethod {
      namespace model {
        class ch.kbw.endpointmethod.model.PointManager {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.endpointmethod {
      namespace model {
        class ch.kbw.endpointmethod.model.Triangle {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.midpointmethod {
      class ch.kbw.midpointmethod.MidPointController {
      }
    }
  }
  

  namespace  {
    namespace h.kbw.midpointmethod {
      namespace model {
        class ch.kbw.midpointmethod.model.CircleModel {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.midpointmethod {
      namespace model {
        class ch.kbw.midpointmethod.model.Line {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.midpointmethod {
      namespace model {
        class ch.kbw.midpointmethod.model.Point {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.midpointmethod {
      namespace model {
        class ch.kbw.midpointmethod.model.PointList {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.midpointmethod {
      namespace model {
        class ch.kbw.midpointmethod.model.TriangleModel {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.radialpointmethod {
      class ch.kbw.radialpointmethod.RadialPointController {
      }
    }
  }
  

  namespace  {
    namespace h.kbw.radialpointmethod {
      namespace model {
        class ch.kbw.radialpointmethod.model.CircleModel {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.radialpointmethod {
      namespace model {
        class ch.kbw.radialpointmethod.model.CircumferencePointModel {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.radialpointmethod {
      namespace model {
        class ch.kbw.radialpointmethod.model.RandomPointModel {
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.radialpointmethod {
      namespace model {
        class ch.kbw.radialpointmethod.model.TriangleModel {
        }
      }
    }
  }
  

  ch.kbw.app.App -up-|> javafx.application.Application
  ch.kbw.app.StartScreenController .up.|> javafx.fxml.Initializable
  ch.kbw.endpointmethod.EndPointController .up.|> javafx.fxml.Initializable
  ch.kbw.endpointmethod.EndPointController o-- ch.kbw.endpointmethod.model.Circle : circle
  ch.kbw.endpointmethod.EndPointController o-- ch.kbw.endpointmethod.model.LineManager : lineManager
  ch.kbw.endpointmethod.EndPointController o-- ch.kbw.endpointmethod.model.PointManager : pointManager
  ch.kbw.endpointmethod.EndPointController o-- ch.kbw.endpointmethod.model.Triangle : triangle
  ch.kbw.midpointmethod.MidPointController .up.|> javafx.fxml.Initializable
  ch.kbw.midpointmethod.MidPointController o-- ch.kbw.midpointmethod.model.CircleModel : cm
  ch.kbw.midpointmethod.MidPointController o-- ch.kbw.midpointmethod.model.PointList : pl
  ch.kbw.radialpointmethod.RadialPointController .up.|> javafx.fxml.Initializable
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.CircleModel : circle
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.CircumferencePointModel : radialPoint
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.RandomPointModel : randomPoint
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.TriangleModel : triangle


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
