@startuml

title __BERTRANDS-PARADOX's Class Diagram__\n



  

  ch.kbw.app.App -up-|> javafx.application.Application
  ch.kbw.app.StartScreenController .up.|> javafx.fxml.Initializable
  ch.kbw.endpointmethod.EndPointController .up.|> javafx.fxml.Initializable
  ch.kbw.endpointmethod.EndPointController o-- ch.kbw.endpointmethod.model.Circle : circle
  ch.kbw.endpointmethod.EndPointController o-- ch.kbw.endpointmethod.model.LineManager : lineManager
  ch.kbw.endpointmethod.EndPointController o-- ch.kbw.endpointmethod.model.PointManager : pointManager
  ch.kbw.endpointmethod.EndPointController o-- ch.kbw.endpointmethod.model.Triangle : triangle
  ch.kbw.midpointmethod.MidPointController .up.|> javafx.fxml.Initializable
  ch.kbw.midpointmethod.MidPointController o-- ch.kbw.midpointmethod.model.CircleModel : cm
  ch.kbw.midpointmethod.MidPointController o-- ch.kbw.midpointmethod.model.PointList : pl
  ch.kbw.radialpointmethod.RadialPointController .up.|> javafx.fxml.Initializable
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.CircleModel : circle
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.CircumferencePointModel : radialPoint
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.RandomPointModel : randomPoint
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.TriangleModel : triangle




@enduml
