@startuml

title __BERTRANDS-PARADOX's Class Diagram__\n

  namespace endpointmethod.controller {
    class endpointmethod.controller.EndPointController {
    }
  }
  

  namespace endpointmethod.model {
    class endpointmethod.model.Circle {
    }
  }
  

  namespace endpointmethod.model {
    class endpointmethod.model.Line {
    }
  }
  

  namespace endpointmethod.model {
    class endpointmethod.model.LineManager {
    }
  }
  

  namespace endpointmethod.model {
    class endpointmethod.model.Point {
    }
  }
  

  namespace endpointmethod.model {
    class endpointmethod.model.PointManager {
    }
  }
  

  namespace endpointmethod.model {
    class endpointmethod.model.Triangle {
    }
  }
  

  namespace midpointmethod.controller {
    class midpointmethod.controller.MidPointController {
    }
  }
  

  namespace midpointmethod.model {
    class midpointmethod.model.CircleModel {
    }
  }
  

  namespace midpointmethod.model {
    class midpointmethod.model.Line {
    }
  }
  

  namespace midpointmethod.model {
    class midpointmethod.model.Point {
    }
  }
  

  namespace midpointmethod.model {
    class midpointmethod.model.PointList {
    }
  }
  

  namespace midpointmethod.model {
    class midpointmethod.model.TriangleModel {
    }
  }
  

  namespace radialpointmethod.controller {
    class radialpointmethod.controller.RadialPointController {
    }
  }
  

  namespace radialpointmethod.model {
    class radialpointmethod.model.CircleModel {
    }
  }
  

  namespace radialpointmethod.model {
    class radialpointmethod.model.CircumferencePointModel {
    }
  }
  

  namespace radialpointmethod.model {
    class radialpointmethod.model.RandomPointModel {
    }
  }
  

  namespace radialpointmethod.model {
    class radialpointmethod.model.TriangleModel {
    }
  }
  

  namespace startscreen {
    class startscreen.MainApp {
    }
  }
  

  namespace startscreen {
    namespace controller {
      class startscreen.controller.StartScreenController {
      }
    }
  }
  

  endpointmethod.controller.EndPointController .up.|> javafx.fxml.Initializable
  endpointmethod.controller.EndPointController o-- endpointmethod.model.Circle : circle
  endpointmethod.controller.EndPointController o-- endpointmethod.model.LineManager : lineManager
  endpointmethod.controller.EndPointController o-- endpointmethod.model.PointManager : pointManager
  endpointmethod.controller.EndPointController o-- endpointmethod.model.Triangle : triangle
  endpointmethod.model.Circle o-- endpointmethod.model.Point : midpoint
  endpointmethod.model.Line o-- endpointmethod.model.Point : endPoint
  endpointmethod.model.Line o-- endpointmethod.model.Point : startPoint
  endpointmethod.model.Triangle o-- endpointmethod.model.Point : firstCorner
  endpointmethod.model.Triangle o-- endpointmethod.model.Point : secondCorner
  endpointmethod.model.Triangle o-- endpointmethod.model.Point : thirdCorner
  midpointmethod.controller.MidPointController .up.|> javafx.fxml.Initializable
  midpointmethod.controller.MidPointController o-- midpointmethod.model.CircleModel : cm
  midpointmethod.controller.MidPointController o-- midpointmethod.model.PointList : pl
  radialpointmethod.controller.RadialPointController .up.|> javafx.fxml.Initializable
  radialpointmethod.controller.RadialPointController o-- radialpointmethod.model.CircleModel : circle
  radialpointmethod.controller.RadialPointController o-- radialpointmethod.model.CircumferencePointModel : radialPoint
  radialpointmethod.controller.RadialPointController o-- radialpointmethod.model.RandomPointModel : randomPoint
  radialpointmethod.controller.RadialPointController o-- radialpointmethod.model.TriangleModel : triangle
  startscreen.MainApp -up-|> javafx.application.Application
  startscreen.controller.StartScreenController .up.|> javafx.fxml.Initializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
