@startuml

title __MODEL's Class Diagram__\n

  namespace  {
    namespace h.kbw.midpointmethod {
      namespace model {
        class ch.kbw.midpointmethod.model.CircleModel {
            - r : double
            - x : double
            - y : double
            + CircleModel()
            + CircleModel()
            + generatePointsInCircleModel()
            + getR()
            + getX()
            + getY()
            + setR()
            + setX()
            + setY()
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.midpointmethod {
      namespace model {
        class ch.kbw.midpointmethod.model.Line {
            - endX : double
            - endY : double
            - startX : double
            - startY : double
            + Line()
            + getEndX()
            + getEndY()
            + getStartX()
            + getStartY()
            + setEndX()
            + setEndY()
            + setStartX()
            + setStartY()
            + toString()
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.midpointmethod {
      namespace model {
        class ch.kbw.midpointmethod.model.Point {
            - check : boolean
            - inInnerCircle : boolean
            - x : double
            - y : double
            + Point()
            + calculateIntersection()
            + getLine()
            + getX()
            + getY()
            + isCheck()
            + isInInnerCircle()
            + setCheck()
            + setInInnerCircle()
            + setX()
            + setY()
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.midpointmethod {
      namespace model {
        class ch.kbw.midpointmethod.model.PointList {
            - points : ArrayList<Point>
            + PointList()
            + addPoint()
            + calculateHitRate()
            + clearList()
            + getPoint()
            + getPoints()
            + getSizeofPoints()
            + setPoints()
        }
      }
    }
  }
  

  namespace  {
    namespace h.kbw.midpointmethod {
      namespace model {
        class ch.kbw.midpointmethod.model.TriangleModel {
            - A : Double
            - B : Double
            - C : Double
            - h : double
            - length : double
            + TriangleModel()
            + getA()
            + getB()
            + getC()
            + getH()
            + getLength()
            + getXPoints()
            + getYPoints()
            + setA()
            + setB()
            + setC()
            + setH()
            + setLength()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
