@startuml

title __RADIALPOINTMETHOD's Class Diagram__\n

  namespace  {
    namespace h.kbw.radialpointmethod {
      class ch.kbw.radialpointmethod.RadialPointController {
          - angle : TextField
          - canvas : Canvas
          - delay : TextField
          - gc : GraphicsContext
          - iterations : TextField
          - manualRad : RadioButton
          - menubutton : Button
          - probLabel : Label
          - randomRad : RadioButton
          - resetbutton : Button
          - startbutton : Button
          + RadialPointController()
          + disableGUI()
          + drawAndClear()
          + drawCircle()
          + drawRadius()
          + drawRandomLines()
          + drawTriangle()
          + handleButtonMenu()
          + handleButtonReset()
          + handleButtonStart()
          + initialize()
          + radioButtonManual()
          + radioButtonRandom()
      }
    }
  }
  

  ch.kbw.radialpointmethod.RadialPointController .up.|> javafx.fxml.Initializable
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.CircleModel : circle
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.CircumferencePointModel : radialPoint
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.RandomPointModel : randomPoint
  ch.kbw.radialpointmethod.RadialPointController o-- ch.kbw.radialpointmethod.model.TriangleModel : triangle


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
