@startuml

title __MODEL's Class Diagram__\n

  namespace radialpointmethod.model {
    class radialpointmethod.model.CircleModel {
        - radius : double
        - xPos : double
        - yPos : double
        + CircleModel()
        + getDiameter()
        + getRadius()
        + getXPosCenter()
        + getxPos()
        + getyPos()
        + getyPosCenter()
        + setPos()
        + setPos()
        + setRadius()
        + setyPos()
    }
  }
  

  namespace radialpointmethod.model {
    class radialpointmethod.model.CircumferencePointModel {
        - radialPoint : Double
        + CircumferencePointModel()
        + getRadialPoint()
        + setAngleCircumferencePoint()
        + setRandomCircumferencePoint()
    }
  }
  

  namespace radialpointmethod.model {
    class radialpointmethod.model.RandomPointModel {
        + RandomPointModel()
        + calculateIntersection()
        + createSingleVectorPoint()
        + getEndPoint()
        + isLineLonger()
    }
  }
  

  namespace radialpointmethod.model {
    class radialpointmethod.model.TriangleModel {
        - A : Double
        - B : Double
        - C : Double
        - height : double
        - length : double
        + TriangleModel()
        + getA()
        + getB()
        + getC()
        + getHeight()
        + getLength()
        + getXPoints()
        + getYPoints()
        + setA()
        + setB()
        + setC()
        + setHeight()
        + setLength()
        + setPosInCircle()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
